TERMUX_PKG_HOMEPAGE=https://github.com/REAndroid/APKEditor
TERMUX_PKG_DESCRIPTION="Android binary resource files editor"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@Veha0001"
TERMUX_PKG_VERSION="1.4.8"
TERMUX_PKG_SRCURL=https://github.com/REAndroid/APKEditor/releases/download/V${TERMUX_PKG_VERSION}/APKEditor-${TERMUX_PKG_VERSION}.jar
TERMUX_PKG_SHA256=026906af28497577496a3e1f5054a878a7cf9c1b3889626882d87ea88d09c20f
TERMUX_PKG_DEPENDS="openjdk-21"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_SKIP_SRC_EXTRACT=true
TERMUX_PKG_PLATFORM_INDEPENDENT=true
TERMUX_PKG_UPDATE_TAG_TYPE="latest-release-tag"
TERMUX_PKG_UPDATE_VERSION_REGEXP="\d+\.\d+\.\d+"

termux_step_make_install() {
	local RAWJAR="$TERMUX_PKG_CACHEDIR/APKEditor-${TERMUX_PKG_VERSION}.jar"
	termux_download $TERMUX_PKG_SRCURL $RAWJAR $TERMUX_PKG_SHA256
	install -Dm600 $RAWJAR $TERMUX_PREFIX/libexec/apkeditor/apkeditor.jar
	sed -e "s|@TERMUX_PREFIX@|$TERMUX_PREFIX|g" \
		$TERMUX_PKG_BUILDER_DIR/wrapper.in \
		> $TERMUX_PREFIX/bin/$TERMUX_PKG_NAME
	chmod 700 $TERMUX_PREFIX/bin/$TERMUX_PKG_NAME
}
